soundtrack_choices = [
    'ANOTHER HIM',
    'Beginning',
    'School',
    'Susie',
    'The Door',
    'Cliffs',
    'The Chase',
    'The Legend',
    'Lancer',
    'Rude Buster',
    'Empty Town',
    'Weird Birds',
    'Field of Hopes and Dreams',
    'Fanfare (from Rose of Winter)',
    'Lantern',
    "I'm Very Bad",
    'Checker Dance',
    'Quiet Autumn',
    'Scarlet Forest',
    'Thrash Machine',
    'Vs. Lancer',
    'Basement',
    'Imminent Death',
    'Vs. Susie',
    'Card Castle',
    'Rouxls Kaard',
    'April 2012',
    'Hip Shop',
    'Gallery',
    'Chaos King',
    'Darkness Falls',
    'The Circus',
    'THE WORLD REVOLVING',
    'Friendship',
    'THE HOLY',
    'Your Power',
    'A Town Called Hometown',
    'You Can Always Come Home',
    "Don't Forget",
    'Before the Story',
    'Faint Glow',
    'Girl Next Door',
    'My Castle Town',
    'Ohhhhohohoho!',
    'Queen',
    "A CYBER'S WORLD?",
    'A Simple Diversion',
    'Almost To The Guys!',
    'Cool Beat',
    'When I Get Mad I Dance Like This',
    'Cyber Battle (Solo)',
    'When I Get Happy I Dance Like This',
    'Sound Studio',
    'Berdly',
    'Smart Race',
    'Faint Courage (Game Over)',
    'WELCOME TO THE CITY',
    'Mini Studio',
    'Holiday Studio',
    'Cool Mixtape',
    'HEY EVERY !',
    'Spamton',
    "NOW'S YOUR CHANCE TO BE A",
    'Elegant Entrance',
    'Bluebird of Misfortune',
    'Pandora Palace',
    'KEYGEN',
    'Acid Tunnel of Love',
    'It\'s Pronounced "Rules"',
    'Lost Girl',
    'Ferris Wheel',
    'Attack of the Killer Queen',
    'Giga Size',
    'Powers Combined',
    'Knock You Down !!',
    'The Dark Truth',
    'Digital Roots',
    'Deal Gone Wrong',
    'BIG SHOT',
    'A Real Boy!',
    'Dialtone',
    'sans.',
    'Chill Jailbreak Alarm To Study And Relax To',
    'You Can Always Come Home',
    'Until Next Time',
    'Before The Story',
    'Berdly (Rejected Concept)'
    ]